#!/bin/bash
#
# Script to build transpiler Docker image.
#
# Needs root privileges or 'docker' group membership

SCRIPT_DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
. "${SCRIPT_DIR}/../inc.constants"
. "${SCRIPT_DIR}/../inc.functions"


# Functions
function usage {
    echo -e "Usage: ${0} [OPTIONS]"
    echo -e "  --kotlin-version VERSION\t(default: ${DEFAULT_KOTLIN_VERSION})"
    echo -e "  --docker-push\t\t\t(optional)"
    exit 1
}


# Command-line arguments
kotlin_version=${DEFAULT_KOTLIN_VERSION}
while [[ $# -gt 0 ]] ; do
    key="$1"
    case $key in
    --kotlin-version)
        kotlin_version="$2"
        shift # past argument
        ;;
    --docker-push)
        docker_push=true
        ;;
    -h|--help)
        usage
        shift # past argument
        ;;
    *) # unknown option
        ;;
    esac
    shift # past argument or value
done


# Let's roll
image_tag=${kotlin_version}

safe docker build \
    --build-arg kotlin_version=${kotlin_version} \
    --tag ${DOCKER_IMAGE}:${image_tag} .
if [ ${docker_push} ] ; then
    safe docker push ${DOCKER_IMAGE}:${image_tag}
fi

# Update 'latest' tag if script argument match defaults
if [ ${kotlin_version} = ${DEFAULT_KOTLIN_VERSION} ]; then
    safe docker tag ${DOCKER_IMAGE}:${image_tag} ${DOCKER_IMAGE}:latest
    if [ ${docker_push} ] ; then
        safe docker push ${DOCKER_IMAGE}:latest
    fi
fi
